name = "NextGP"
uuid = "1a32220a-4ac3-442e-849d-1943511e16f7"
authors = ["Emre Karaman <emrkaraman@gmail.com> and contributors"]
version = "0.1.0"

[deps]

[compat]
DataFrames = "1.3.2"
DataStructures = "0.18"
Distributions = "0.25.58"
MCMCChains = "5"
MixedModels = "4.6.0"
ProgressMeter = "1"
StatsBase = "0.33"
StatsModels = "0.6.3"
StatsPlots = "0.14"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
