name = "NextGP"
uuid = "1a32220a-4ac3-442e-849d-1943511e16f7"
authors = ["Emre Karaman <emrkaraman@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1"
DataFrames = "1.3.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
